CC=gcc

plotz2_pt1:	plotz2_pt1.o
	$(CC) -Wall -Wstrict-prototypes -o plotz2_pt1 plotz2_pt1.o -lm

plotz2_pt2:	plotz2_pt2.o
	$(CC) -Wall -Wstrict-prototypes -o plotz2_pt2 plotz2_pt2.o -lm

plotz2_pt3:	plotz2_pt3.o
	$(CC) -Wall -Wstrict-prototypes -o plotz2_pt3 plotz2_pt3.o -lm

plotz2_pt4:	plotz2_pt4.o
	$(CC) -Wall -Wstrict-prototypes -o plotz2_pt4 plotz2_pt4.o -lm

.PHONY: clean

clean:
	rm ./plotz2_pt1.o
	rm ./plotz2_pt2.o
	rm ./plotz2_pt3.o
	rm ./plotz2_pt4.o

.PHONY: immaculate

immaculate:
	rm ./plotz2_pt1.o
	rm ./plotz2_pt1
	rm ./plotz2_pt2.o
	rm ./plotz2_pt2
	rm ./plotz2_pt3.o
	rm ./plotz2_pt3
	rm ./plotz2_pt4.o
	rm ./plotz2_pt4
