C=gcc

codestats: codestats_pt1.o codestats_pt2.o codestats_pt3.o codestats_pt4.o codestats_pt5.o codestats_pt6.o codestats_pt7.o
	$(CC) -Wall -o codestats_pt1 codestats_pt1.o
	$(CC) -Wall -o codestats_pt2 codestats_pt2.o
	$(CC) -Wall -o codestats_pt3 codestats_pt3.o
	$(CC) -Wall -o codestats_pt4 codestats_pt4.o
	$(CC) -Wall -o codestats_pt5 codestats_pt5.o
	$(CC) -Wall -o codestats_pt6 codestats_pt6.o
	$(CC) -Wall -o codestats_pt7 codestats_pt7.o

.PHONY: clean

clean:
	rm ./codestats_pt1.o
	rm ./codestats_pt2.o
	rm ./codestats_pt3.o
	rm ./codestats_pt4.o
	rm ./codestats_pt5.o
	rm ./codestats_pt6.o
	rm ./codestats_pt7.o

.PHONY: immaculate

immaculate:
	rm ./codestats_pt1.o
	rm ./codestats_pt2.o
	rm ./codestats_pt3.o
	rm ./codestats_pt4.o
	rm ./codestats_pt5.o
	rm ./codestats_pt6.o
	rm ./codestats_pt7.o
	rm ./codestats_pt1
	rm ./codestats_pt2
	rm ./codestats_pt3
	rm ./codestats_pt4
	rm ./codestats_pt5
	rm ./codestats_pt6
	rm ./codestats_pt7
